<?php
/**
 * Liquid Messages Main Shortcode - Run
 *
 * @package Liquid Messages
 */

class GCSS_Sermons_Run extends GCS_Shortcodes_Run_Base
{

    /** @var int $inception_levels Keep track of levels of inception */
    protected static $inception_levels = 0;

    /** @var string $shortcode The shortcode tag */
    public $shortcode = 'gc_sermons';

    /** @var array $atts_defaults Array of default attributes applied to the shortcode */
    public $atts_defaults = array(
        'per_page'          => 10, // Will use WP's per-page option.
        'content'           => 'excerpt',
        'remove_thumbnail'  => false,
        'thumbnail_size'    => 'medium',
        'number_columns'    => 2,
        'list_offset'       => 0,
        'wrap_classes'      => '',
        'remove_pagination' => false,
        'related_speaker'   => 0,
        'related_series'    => 0,
    );

    /** @var GCS_Taxonomies GCS_Taxonomies Object */
    public $taxonomies;

    /**
     * Constructor
     *
     * @since 0.1.3
     *
     * @param GCS_Sermons    $sermons
     * @param GCS_Taxonomies $taxonomies
     */
    public function __construct(GCS_Sermons $sermons, GCS_Taxonomies $taxonomies)
    {
        $this->taxonomies = $taxonomies;
        parent::__construct($sermons);
    }

    /**
     * Shortcode Output
     *
     * The output generated by utilizing this shortcode.
     */
    public function shortcode()
    {
        /*
         * Because it's possible to trigger inception, we need to keep track which
         * level we are in, and reset the shortcode object accordingly.
         *
         * Clever alert. The ++ happens AFTER the value is read, So $my_level starts at 0.
         */
        $my_level = self::$inception_levels++;

        $args = $this->map_related_term_args($this->get_initial_query_args());

        if (!$args) {
            // We failed the related term check.
            return '';
        }

        // If it is not an excluded post / it is singular / and is of the desired post type
        if (!isset($args['post__not_in']) && is_singular($this->sermons->post_type())) {
            // Make it an excluded post
            $args['post__not_in'] = array(get_queried_object_id());
        } elseif(is_singular($this->sermons->post_type())) {
            // Get posts that have specified meta_key with value
            $get_video_post = get_posts(array(
                'post_type' => $this->sermons->post_type(),
                'meta_key' => 'gc_exclude_msg',
                'meta_value' => 'on',
            ));

            // Retrieve the ID field from each post
            $get_video_post_ids = wp_list_pluck($get_video_post, 'ID');

            // Merge our lists of excluded messages.
            $args['post__not_in'] = array_unique(array_merge($args['post__not_in'], $get_video_post_ids));
        }

        $sermons = $this->sermons->get_many($args);

        if (!$sermons->have_posts()) {
            return '';
        }

        $max     = $sermons->max_num_pages;
        $sermons = $this->map_sermon_args($sermons, $my_level);

        $content = '';
        if ( $my_level === 0 ) {
            $content .= GCS_Style_Loader::get_template('list-item-style');
        }

        $args = $this->get_pagination($max);
        $args['wrap_classes']  = $this->get_wrap_classes();
        $args['sermons']       = $sermons;
        $args['plugin_option'] = get_plugin_settings_options('single_message_view');

        $content .= GCS_Template_Loader::get_template('sermons-list', $args);

        return $content;
    }

	/**
	 * Map Related Term Args
	 *
	 * @param $args
	 *
	 * @return bool
	 */
    protected function map_related_term_args($args)
    {

        $required = false;
        $passes   = false;
        $keys     = array(
            'series'  => 'related_series',
            'speaker' => 'related_speaker',
        );

        foreach ($keys as $key => $param) {

            if ($term_id = absint($this->att($param))) {

                $args['tax_query'][] = array(
                    'taxonomy' => $this->taxonomies->{$key}->taxonomy(),
                    'field'    => 'id',
                    'terms'    => $term_id,
                );

                continue;
            }

            if ( $this->att($param) !== 'this' ) {
                continue;
            }

            $required = true;

            try {
                $sermon = gc_get_sermon_post(get_queried_object(), true);

                $args['post__not_in'] = array($sermon->ID);

                $method = 'get_' . $key;
                $term   = $sermon->$method();

                if (!$term) {
                    throw new Exception('No ' . $key . ' term.');
                }

            } catch(Exception $e) {
                continue;
            }

            $passes = true;

            $args['tax_query'][] = array(
                'taxonomy' => $this->taxonomies->{$key}->taxonomy(),
                'field'    => 'id',
                'terms'    => $term->term_id,
            );

        }

        if ($required && !$passes) {
            // They wanted messages associated to 'this', but that's not possible.
            return false;
        }

        return $args;
    }

	/**
	 * Get Initial Query Args
	 *
	 * @return array
	 */
    public function get_initial_query_args()
    {
        $posts_per_page = (int)$this->att('per_page', get_option('posts_per_page'));
        $paged          = (int)get_query_var('paged') ? get_query_var('paged') : 1;
        $offset         = (($paged - 1) * $posts_per_page) + $this->att('list_offset', 0);

        return compact('posts_per_page', 'paged', 'offset');
    }

	/**
	 * Map Message Args
	 *
	 * @param $all_sermons
	 * @param $my_level
	 *
	 * @return array
	 */
    protected function map_sermon_args($all_sermons, $my_level)
    {
        global $post;
        $sermons = array();

        $do_thumb        = !$this->bool_att('remove_thumbnail');
        $do_content      = $this->bool_att('content');
        $type_of_content = $this->att('content');
        $thumb_size      = $this->att('thumbnail_size');

        while ($all_sermons->have_posts()) {
            $all_sermons->the_post();

            $obj = $all_sermons->post;

            $sermon = array();
            $sermon['url']            = $obj->permalink();
            $sermon['name']           = $obj->title();
            $sermon['image']          = $do_thumb ? $obj->featured_image($thumb_size) : '';
            $sermon['do_image']       = (bool)$sermon['image'];
            $sermon['description']    = '';
            $sermon['do_description'] = $do_content;
            if ($do_content) {
                $sermon['description'] = $type_of_content === 'excerpt'
                    ? $obj->loop_excerpt()
                    : apply_filters('the_content', $obj->post_content);
            }

            $sermons[] = $sermon;
        }

        wp_reset_postdata();

        if ($do_content) {
            /*
             * Reset shortcode_object as well, as calling the content/excerpt
             * could trigger inception and change the object under us.
             */
            $this->shortcode_object = WDS_Shortcode_Instances::get($this->shortcode, $my_level);
        }

        return $sermons;
    }

	/**
	 * Get Pagination
	 *
	 * @param $total_pages
	 *
	 * @return array
	 */
    protected function get_pagination($total_pages)
    {
        $nav = array('prev_link' => '', 'next_link' => '');

        if (!$this->bool_att('remove_pagination')) {
            $nav['prev_link'] = get_previous_posts_link(__('<span>&larr;</span> Newer', 'lqdm'));
            $nav['next_link'] = get_next_posts_link(__('Older <span>&rarr;</span>', 'lqdm'), $total_pages);
        }

        return $nav;
    }

	/**
	 * Get Wrap Classes
	 *
	 * @return string
	 */
    protected function get_wrap_classes()
    {
        $columns = absint($this->att('number_columns'));
        $columns = $columns < 1 ? 1 : $columns;

        return $this->att('wrap_classes') . ' lqdm-' . $columns . '-cols lqdm-msgs-wrap';
    }
}
